
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./Navbar";
import { Toaster } from "sonner";
import MySessionProvider from "@/app/_providers/MySessionProvider";
import CartContextProvider from "./_context/CartContextProvider";
import { getUserCart } from "./_actions/cart.action";
import  Footer  from '@/app/Footer';


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const userCart = await getUserCart()
  
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col overflow-x-hidden">
        <MySessionProvider>
        <CartContextProvider userCart={userCart!}>
        
        <Toaster />
        <Navbar/>
        {children}
        
        <Footer/>

        </CartContextProvider>
        </MySessionProvider>
        </body>
    </html>
  );
}
